// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NotificationLog.RentalService.IntegrationTests.Features.Visitors
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class FichaDelVisitanteFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features/Visitors", "Ficha del visitante", "  La ficha reúne las visitas del visitante, sus inasistencias, lo que sigue y su " +
                "actividad.\r\n  Todo sale del registro del visitante, que se mantiene al día con c" +
                "ada paso de sus visitas.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "FichaDeVisitante.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("que ahora son las \"2026-10-05 09:00\" hora de Colombia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 8
    await testRunner.AndAsync("el usuario \"Ana\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario \"Víctor\" con rol Visitor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 10
    await testRunner.AndAsync("el usuario \"Valeria\" con rol Visitor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 11
    await testRunner.AndAsync("el usuario \"Marta\" con rol Moderador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 12
    await testRunner.AndAsync("que \"Ana\" está registrada como propietaria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 13
    await testRunner.AndAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Visitors/FichaDeVisitante.feature.ndjson", 8);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("La ficha muestra la visita que pidió el visitante")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("La ficha muestra la visita que pidió el visitante")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task LaFichaMuestraLaVisitaQuePidioElVisitante()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("La ficha muestra la visita que pidió el visitante", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 16
    await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.WhenAsync("\"Marta\" consulta el registro de visitante de \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 18
    await testRunner.ThenAsync("el visitante tiene 1 visita y 0 inasistencias", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 19
    await testRunner.AndAsync("la visita del visitante está en estado \"Esperando al anfitrión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 20
    await testRunner.AndAsync("lo que sigue para el visitante es \"Esperando al anfitrión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cuando el anfitrión propone otras franjas, al visitante le toca responder")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cuando el anfitrión propone otras franjas, al visitante le toca responder")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task CuandoElAnfitrionProponeOtrasFranjasAlVisitanteLeTocaResponder()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cuando el anfitrión propone otras franjas, al visitante le toca responder", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 23
    await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table10.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 24
    await testRunner.WhenAsync("\"Ana\" propone otras franjas:", ((string)(null)), table10, "Cuando ");
#line hidden
#line 27
    await testRunner.AndAsync("\"Marta\" consulta el registro de visitante de \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 28
    await testRunner.ThenAsync("la visita del visitante está en estado \"Esperando al visitante\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 29
    await testRunner.AndAsync("lo que sigue para el visitante es \"Esperando al visitante\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una inasistencia queda en el registro del visitante")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una inasistencia queda en el registro del visitante")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task UnaInasistenciaQuedaEnElRegistroDelVisitante()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una inasistencia queda en el registro del visitante", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 33
    await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 11:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 34
    await testRunner.AndAsync("\"Ana\" marca que el visitante no asistió", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 35
    await testRunner.AndAsync("\"Marta\" consulta el registro de visitante de \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 36
    await testRunner.ThenAsync("el visitante tiene 1 visita y 1 inasistencia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 37
    await testRunner.AndAsync("la visita del visitante está en estado \"No asistió\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 38
    await testRunner.AndAsync("el visitante no tiene nada pendiente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("La actividad cuenta lo que pasó, de lo más reciente a lo más antiguo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("La actividad cuenta lo que pasó, de lo más reciente a lo más antiguo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task LaActividadCuentaLoQuePasoDeLoMasRecienteALoMasAntiguo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("La actividad cuenta lo que pasó, de lo más reciente a lo más antiguo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.AndAsync("que \"Ana\" agendó la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 43
    await testRunner.WhenAsync("\"Víctor\" confirma el correo \"nuevo@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 44
    await testRunner.AndAsync("\"Marta\" consulta el registro de visitante de \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "acción"});
                table11.AddRow(new string[] {
                            "cambió su correo"});
                table11.AddRow(new string[] {
                            "agendó la visita"});
                table11.AddRow(new string[] {
                            "pidió una visita"});
                table11.AddRow(new string[] {
                            "se registró"});
#line 45
    await testRunner.ThenAsync("la actividad del visitante es:", ((string)(null)), table11, "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Moderación filtra visitantes con y sin visitas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Moderación filtra visitantes con y sin visitas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task ModeracionFiltraVisitantesConYSinVisitas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Moderación filtra visitantes con y sin visitas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 54
    await testRunner.WhenAsync("\"Marta\" lista los visitantes con visitas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 55
    await testRunner.ThenAsync("la lista contiene 1 visitante", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 56
    await testRunner.WhenAsync("\"Marta\" lista los visitantes sin visitas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 57
    await testRunner.ThenAsync("la lista contiene 1 visitante", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Moderación ordena los visitantes por más visitas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Moderación ordena los visitantes por más visitas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ficha del visitante")]
        public async global::System.Threading.Tasks.Task ModeracionOrdenaLosVisitantesPorMasVisitas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Moderación ordena los visitantes por más visitas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 61
    await testRunner.WhenAsync("\"Marta\" lista los visitantes por más visitas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 62
    await testRunner.ThenAsync("el primer visitante de la lista es \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
