// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NotificationLog.RentalService.IntegrationTests.Features.Visits
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CancelacionYCierreDeUnaVisitaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features/Visits", "Cancelación y cierre de una visita", "  Cualquiera de las dos partes puede cancelar antes de que la visita empiece.\r\n  " +
                "Después de la hora agendada, el anfitrión la marca como realizada o como inasist" +
                "encia.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CierreDeVisita.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("que ahora son las \"2026-10-05 09:00\" hora de Colombia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 8
    await testRunner.AndAsync("el usuario \"Ana\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario \"Víctor\" con rol Visitor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 10
    await testRunner.AndAsync("que \"Ana\" está registrada como propietaria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 11
    await testRunner.AndAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Visits/CierreDeVisita.feature.ndjson", 14);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El anfitrión cancela una visita en negociación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El anfitrión cancela una visita en negociación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task ElAnfitrionCancelaUnaVisitaEnNegociacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El anfitrión cancela una visita en negociación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una visita en negociación o agendada se puede cancelar indicando el motivo", null, tagsOfRule);
#line 15
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 16
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
      await testRunner.WhenAsync("\"Ana\" cancela la visita con el motivo \"El inmueble ya no está disponible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 18
      await testRunner.ThenAsync("la visita queda en estado \"Cancelada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 19
      await testRunner.AndAsync("la visita fue cancelada por el anfitrión con el motivo \"El inmueble ya no está di" +
                        "sponible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 20
      await testRunner.AndAsync("se notifica \"visita.cancelada\" a \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cancelar exige un motivo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cancelar exige un motivo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task CancelarExigeUnMotivo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar exige un motivo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una visita en negociación o agendada se puede cancelar indicando el motivo", null, tagsOfRule);
#line 22
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 23
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 24
      await testRunner.WhenAsync("\"Víctor\" cancela la visita con el motivo \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 25
      await testRunner.ThenAsync("la solicitud se rechaza por validación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cancelar una visita ya cancelada no tiene efecto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cancelar una visita ya cancelada no tiene efecto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task CancelarUnaVisitaYaCanceladaNoTieneEfecto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar una visita ya cancelada no tiene efecto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una visita en negociación o agendada se puede cancelar indicando el motivo", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" cancelada por \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 29
      await testRunner.WhenAsync("\"Víctor\" cancela la visita con el motivo \"Ya no me interesa\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 30
      await testRunner.ThenAsync("la solicitud se acepta", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 31
      await testRunner.AndAsync("la visita fue cancelada por el anfitrión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 32
      await testRunner.AndAsync("no se envía ninguna notificación nueva", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cancelación de una visita agendada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cancelación de una visita agendada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Víctor", "2026-10-06 21:00", "no es tardía", "3", null, DisplayName="Cancelación de una visita agendada(Víctor,2026-10-06 21:00,no es tardía,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Víctor", "2026-10-07 08:00", "es tardía", "4", null, DisplayName="Cancelación de una visita agendada(Víctor,2026-10-07 08:00,es tardía,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Ana", "2026-10-07 08:00", "no es tardía", "5", null, DisplayName="Cancelación de una visita agendada(Ana,2026-10-07 08:00,no es tardía,5)")]
        public async global::System.Threading.Tasks.Task CancelacionDeUnaVisitaAgendada(string quien, string momento, string resultado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("quién", quien);
            argumentsOfScenario.Add("momento", momento);
            argumentsOfScenario.Add("resultado", resultado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelación de una visita agendada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Es cancelación tardía si el visitante cancela a menos de 12 horas de la visita", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 40
      await testRunner.WhenAsync(string.Format("el reloj avanza hasta las \"{0}\"", momento), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 41
      await testRunner.AndAsync(string.Format("\"{0}\" cancela la visita con el motivo \"No puedo asistir\"", quien), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 42
      await testRunner.ThenAsync("la visita queda en estado \"Cancelada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 43
      await testRunner.AndAsync(string.Format("la cancelación {0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede cancelar una visita que ya empezó")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede cancelar una visita que ya empezó")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedeCancelarUnaVisitaQueYaEmpezo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede cancelar una visita que ya empezó", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Es cancelación tardía si el visitante cancela a menos de 12 horas de la visita", null, tagsOfRule);
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 52
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 10:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 53
      await testRunner.AndAsync("\"Víctor\" cancela la visita con el motivo \"No puedo asistir\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 54
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"La visita ya empezó;" +
                        " no se puede cancelar.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El anfitrión marca la visita como realizada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El anfitrión marca la visita como realizada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task ElAnfitrionMarcaLaVisitaComoRealizada()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El anfitrión marca la visita como realizada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el anfitrión cierra la visita, y solo después de la hora agendada", null, tagsOfRule);
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 62
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 11:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 63
      await testRunner.AndAsync("\"Ana\" marca la visita como realizada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 64
      await testRunner.ThenAsync("la visita queda en estado \"Realizada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 65
      await testRunner.AndAsync("se notifica \"visita.realizada\" a \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El anfitrión marca que el visitante no asistió")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El anfitrión marca que el visitante no asistió")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task ElAnfitrionMarcaQueElVisitanteNoAsistio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El anfitrión marca que el visitante no asistió", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el anfitrión cierra la visita, y solo después de la hora agendada", null, tagsOfRule);
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 68
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 11:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 69
      await testRunner.AndAsync("\"Ana\" marca que el visitante no asistió", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 70
      await testRunner.ThenAsync("la visita queda en estado \"No asistió\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 71
      await testRunner.AndAsync("se notifica \"visita.inasistencia\" a \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede cerrar una visita que todavía no ha empezado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede cerrar una visita que todavía no ha empezado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedeCerrarUnaVisitaQueTodaviaNoHaEmpezado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede cerrar una visita que todavía no ha empezado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el anfitrión cierra la visita, y solo después de la hora agendada", null, tagsOfRule);
#line 73
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 74
      await testRunner.WhenAsync("\"Ana\" marca la visita como realizada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 75
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"La visita todavía no" +
                        " ha empezado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El visitante no puede cerrar la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El visitante no puede cerrar la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task ElVisitanteNoPuedeCerrarLaVisita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El visitante no puede cerrar la visita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el anfitrión cierra la visita, y solo después de la hora agendada", null, tagsOfRule);
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 78
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 11:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 79
      await testRunner.AndAsync("\"Víctor\" marca la visita como realizada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 80
      await testRunner.ThenAsync("la solicitud se rechaza por permisos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una visita cerrada no se puede volver a cerrar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una visita cerrada no se puede volver a cerrar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Cancelación y cierre de una visita")]
        public async global::System.Threading.Tasks.Task UnaVisitaCerradaNoSePuedeVolverACerrar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una visita cerrada no se puede volver a cerrar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el anfitrión cierra la visita, y solo después de la hora agendada", null, tagsOfRule);
#line 82
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("una visita de \"Víctor\" a la publicación de \"Ana\" agendada para el \"2026-10-07 10:" +
                        "00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 83
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-07 11:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 84
      await testRunner.AndAsync("\"Ana\" marca la visita como realizada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 85
      await testRunner.AndAsync("\"Ana\" marca que el visitante no asistió", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 86
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"Solo se puede cerrar" +
                        " una visita agendada.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
