// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NotificationLog.RentalService.IntegrationTests.Features.Visits
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class NegociacionDeUnaVisitaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features/Visits", "Negociación de una visita", "  Un visitante pide una visita proponiendo de 1 a 3 franjas. El anfitrión y el vi" +
                "sitante\r\n  se turnan: quien tiene el turno acepta una franja o propone otras, an" +
                "tes de que venza el plazo.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "NegociacionDeVisita.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("que ahora son las \"2026-10-05 09:00\" hora de Colombia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 8
    await testRunner.AndAsync("el usuario \"Ana\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario \"Pedro\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 10
    await testRunner.AndAsync("el usuario \"Víctor\" con rol Visitor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 11
    await testRunner.AndAsync("el usuario \"Marta\" con rol Moderador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 12
    await testRunner.AndAsync("que \"Ana\" está registrada como propietaria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 13
    await testRunner.AndAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Visits/NegociacionDeVisita.feature.ndjson", 22);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un visitante pide una visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un visitante pide una visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task UnVisitantePideUnaVisita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un visitante pide una visita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo un visitante registrado puede pedir visita a una publicación publicada", null, tagsOfRule);
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table15.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table15.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 18
      await testRunner.WhenAsync("\"Víctor\" pide una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table15, "Cuando ");
#line hidden
#line 22
      await testRunner.ThenAsync("la visita queda en estado \"Esperando al anfitrión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 23
      await testRunner.AndAsync("la visita tiene 2 franjas propuestas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 24
      await testRunner.AndAsync("el plazo para responder vence el \"2026-10-06 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 25
      await testRunner.AndAsync("se notifica \"visita.solicitada\" a \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un usuario que no es visitante no puede pedir visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un usuario que no es visitante no puede pedir visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task UnUsuarioQueNoEsVisitanteNoPuedePedirVisita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un usuario que no es visitante no puede pedir visita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo un visitante registrado puede pedir visita a una publicación publicada", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
      await testRunner.WhenAsync("\"Pedro\" pide una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 29
      await testRunner.ThenAsync("la solicitud se rechaza por validación con el mensaje \"Solo los visitantes pueden" +
                        " pedir una visita.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede pedir visita a una publicación que no está publicada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede pedir visita a una publicación que no está publicada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedePedirVisitaAUnaPublicacionQueNoEstaPublicada()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede pedir visita a una publicación que no está publicada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo un visitante registrado puede pedir visita a una publicación publicada", null, tagsOfRule);
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
      await testRunner.GivenAsync("que \"Ana\" pausó la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 33
      await testRunner.WhenAsync("\"Víctor\" pide una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 34
      await testRunner.ThenAsync("la solicitud se rechaza por validación con el mensaje \"Solo se pueden visitar pub" +
                        "licaciones publicadas.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una franja inválida se rechaza")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una franja inválida se rechaza")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2026-10-06 08:00", "Cada franja debe empezar en al menos 24 horas.", "3", null, DisplayName="Una franja inválida se rechaza(2026-10-06 08:00,Cada franja debe empezar en al me" +
            "nos 24 horas.,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2026-10-20 10:00", "Las franjas no pueden estar a más de 14 días.", "4", null, DisplayName="Una franja inválida se rechaza(2026-10-20 10:00,Las franjas no pueden estar a más" +
            " de 14 días.,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2026-10-07 19:00", "La franja dura una hora y debe empezar entre las 7:00 y las 18:00 hora de Colombi" +
            "a.", "5", null, DisplayName="Una franja inválida se rechaza(2026-10-07 19:00,La franja dura una hora y debe em" +
            "pezar entre las 7:00 y las 18:00 hora de Colombia.,5)")]
        public async global::System.Threading.Tasks.Task UnaFranjaInvalidaSeRechaza(string franja, string mensaje, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("franja", franja);
            argumentsOfScenario.Add("mensaje", mensaje);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una franja inválida se rechaza", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Las franjas duran una hora, entre 24 horas y 14 días de antelación, en horario de" +
                    " 7:00 a 19:00", null, tagsOfRule);
#line 38
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
      await testRunner.WhenAsync(string.Format("\"Víctor\" pide una visita a la publicación de \"Ana\" para el \"{0}\"", franja), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 40
      await testRunner.ThenAsync(string.Format("la solicitud se rechaza por regla de negocio con el mensaje \"{0}\"", mensaje), ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se pueden proponer más de 3 franjas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se pueden proponer más de 3 franjas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedenProponerMasDe3Franjas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se pueden proponer más de 3 franjas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Las franjas duran una hora, entre 24 horas y 14 días de antelación, en horario de" +
                    " 7:00 a 19:00", null, tagsOfRule);
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table16.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table16.AddRow(new string[] {
                            "2026-10-07 12:00"});
                table16.AddRow(new string[] {
                            "2026-10-08 10:00"});
                table16.AddRow(new string[] {
                            "2026-10-08 12:00"});
#line 49
      await testRunner.WhenAsync("\"Víctor\" pide una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table16, "Cuando ");
#line hidden
#line 55
      await testRunner.ThenAsync("la solicitud se rechaza por validación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Las franjas propuestas no pueden repetirse")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Las franjas propuestas no pueden repetirse")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task LasFranjasPropuestasNoPuedenRepetirse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Las franjas propuestas no pueden repetirse", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Las franjas duran una hora, entre 24 horas y 14 días de antelación, en horario de" +
                    " 7:00 a 19:00", null, tagsOfRule);
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table17.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table17.AddRow(new string[] {
                            "2026-10-07 10:00"});
#line 58
      await testRunner.WhenAsync("\"Víctor\" pide una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table17, "Cuando ");
#line hidden
#line 62
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"Las franjas propuest" +
                        "as no pueden solaparse.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El anfitrión acepta una de las franjas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El anfitrión acepta una de las franjas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task ElAnfitrionAceptaUnaDeLasFranjas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El anfitrión acepta una de las franjas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 72
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table18.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table18.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table18, "Dado ");
#line hidden
#line 73
      await testRunner.WhenAsync("\"Ana\" agenda la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 74
      await testRunner.ThenAsync("la visita queda en estado \"Agendada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 75
      await testRunner.AndAsync("la visita está agendada de \"2026-10-07 10:00\" a \"2026-10-07 11:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 76
      await testRunner.AndAsync("se notifica \"visita.agendada\" a \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El anfitrión propone otras franjas y el visitante acepta")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El anfitrión propone otras franjas y el visitante acepta")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task ElAnfitrionProponeOtrasFranjasYElVisitanteAcepta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El anfitrión propone otras franjas y el visitante acepta", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table19.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table19.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table19, "Dado ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table20.AddRow(new string[] {
                            "2026-10-09 08:00"});
#line 79
      await testRunner.WhenAsync("\"Ana\" propone otras franjas:", ((string)(null)), table20, "Cuando ");
#line hidden
#line 82
      await testRunner.ThenAsync("la visita queda en estado \"Esperando al visitante\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 83
      await testRunner.AndAsync("se notifica \"visita.contrapropuesta\" a \"Víctor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 84
      await testRunner.WhenAsync("\"Víctor\" agenda la visita para el \"2026-10-09 08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 85
      await testRunner.ThenAsync("la visita queda en estado \"Agendada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 86
      await testRunner.AndAsync("se notifica \"visita.agendada\" a \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 87
      await testRunner.AndAsync("el historial de la visita tiene 3 entradas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede responder fuera de turno")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede responder fuera de turno")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedeResponderFueraDeTurno()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede responder fuera de turno", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table21.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table21.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table21, "Dado ");
#line hidden
#line 90
      await testRunner.WhenAsync("\"Víctor\" agenda la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 91
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"No es tu turno de re" +
                        "sponder a esta visita.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Solo se puede aceptar una franja propuesta")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Solo se puede aceptar una franja propuesta")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task SoloSePuedeAceptarUnaFranjaPropuesta()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Solo se puede aceptar una franja propuesta", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 93
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table22.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table22.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table22, "Dado ");
#line hidden
#line 94
      await testRunner.WhenAsync("\"Ana\" agenda la visita para el \"2026-10-09 08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 95
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"La franja elegida no" +
                        " está entre las propuestas.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede responder cuando el plazo ya venció")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede responder cuando el plazo ya venció")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task NoSePuedeResponderCuandoElPlazoYaVencio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede responder cuando el plazo ya venció", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 97
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table23.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table23.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table23, "Dado ");
#line hidden
#line 98
      await testRunner.WhenAsync("el reloj avanza hasta las \"2026-10-06 11:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 99
      await testRunner.AndAsync("\"Ana\" agenda la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 100
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"El plazo para respon" +
                        "der a esta visita ya venció.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una visita agendada ya no admite más propuestas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una visita agendada ya no admite más propuestas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task UnaVisitaAgendadaYaNoAdmiteMasPropuestas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una visita agendada ya no admite más propuestas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Quien tiene el turno acepta una franja propuesta o propone otras", null, tagsOfRule);
#line 102
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table24.AddRow(new string[] {
                            "2026-10-07 10:00"});
                table24.AddRow(new string[] {
                            "2026-10-08 15:00"});
#line 67
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" proponiendo las franjas:", ((string)(null)), table24, "Dado ");
#line hidden
#line 103
      await testRunner.GivenAsync("que \"Ana\" agendó la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "franja"});
                table25.AddRow(new string[] {
                            "2026-10-09 08:00"});
#line 104
      await testRunner.WhenAsync("\"Víctor\" propone otras franjas:", ((string)(null)), table25, "Cuando ");
#line hidden
#line 107
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"La visita ya no está" +
                        " en negociación.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un tercero no puede consultar la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un tercero no puede consultar la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task UnTerceroNoPuedeConsultarLaVisita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un tercero no puede consultar la visita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo los participantes y moderación ven la visita", null, tagsOfRule);
#line 114
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 115
      await testRunner.WhenAsync("\"Pedro\" consulta la visita", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 116
      await testRunner.ThenAsync("la solicitud se rechaza por permisos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un tercero no puede responder a la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un tercero no puede responder a la visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        public async global::System.Threading.Tasks.Task UnTerceroNoPuedeResponderALaVisita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un tercero no puede responder a la visita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo los participantes y moderación ven la visita", null, tagsOfRule);
#line 118
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 119
      await testRunner.WhenAsync("\"Pedro\" agenda la visita para el \"2026-10-07 10:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 120
      await testRunner.ThenAsync("la solicitud se rechaza por permisos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cada usuario lista solo las visitas en las que participa")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cada usuario lista solo las visitas en las que participa")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Negociación de una visita")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Víctor", "1", "16", null, DisplayName="Cada usuario lista solo las visitas en las que participa(Víctor,1,16)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Ana", "1", "17", null, DisplayName="Cada usuario lista solo las visitas en las que participa(Ana,1,17)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Pedro", "0", "18", null, DisplayName="Cada usuario lista solo las visitas en las que participa(Pedro,0,18)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Marta", "1", "19", null, DisplayName="Cada usuario lista solo las visitas en las que participa(Marta,1,19)")]
        public async global::System.Threading.Tasks.Task CadaUsuarioListaSoloLasVisitasEnLasQueParticipa(string usuario, string visitas, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("usuario", usuario);
            argumentsOfScenario.Add("visitas", visitas);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cada usuario lista solo las visitas en las que participa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo los participantes y moderación ven la visita", null, tagsOfRule);
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
      await testRunner.GivenAsync("que \"Víctor\" pidió una visita a la publicación de \"Ana\" para el \"2026-10-07 10:00" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 123
      await testRunner.WhenAsync(string.Format("\"{0}\" lista las visitas", usuario), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 124
      await testRunner.ThenAsync(string.Format("la lista contiene {0} visitas", visitas), ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
