<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Users/user_contact_updated.proto" GrpcServices="None" />
    <Protobuf Include="Notifications/notification_dispatch_requested.proto" GrpcServices="None" />
    <Protobuf Include="Identity/person_verification_changed.proto" GrpcServices="None" />
    <Protobuf Include="Identity/advisor_changed.proto" GrpcServices="None" />
    <Protobuf Include="Identity/alerts_consent_changed.proto" GrpcServices="None" />
    <Protobuf Include="Identity/user_created.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
