<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f8c11649-4e8d-481c-b8dc-2cc632cdac28</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventSourcingLab.ApiService\EventSourcingLab.ApiService.csproj" />
    <ProjectReference Include="..\EventSourcingLab.Web\EventSourcingLab.Web.csproj" />
  </ItemGroup>

</Project>
