// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NotificationLog.RentalService.IntegrationTests.Features.Listings
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CatalogoPublicoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features/Listings", "Catálogo público", "  Cualquier persona, sin iniciar sesión, puede ver las publicaciones publicadas.\r" +
                "\n  Las que están en cualquier otro estado no existen para el catálogo.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Catalogo.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("que ahora son las \"2026-10-05 09:00\" hora de Colombia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 8
    await testRunner.AndAsync("el usuario \"Ana\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 9
    await testRunner.AndAsync("que \"Ana\" está registrada como propietaria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Listings/Catalogo.feature.ndjson", 14);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El catálogo solo lista publicaciones publicadas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El catálogo solo lista publicaciones publicadas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task ElCatalogoSoloListaPublicacionesPublicadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El catálogo solo lista publicaciones publicadas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "operación",
                            "barrio",
                            "estado"});
                table1.AddRow(new string[] {
                            "arriendo",
                            "Chapinero",
                            "Publicada"});
                table1.AddRow(new string[] {
                            "venta",
                            "Usaquén",
                            "Publicada"});
                table1.AddRow(new string[] {
                            "arriendo",
                            "Suba",
                            "Borrador"});
                table1.AddRow(new string[] {
                            "arriendo",
                            "Teusaquillo",
                            "En revisión"});
                table1.AddRow(new string[] {
                            "venta",
                            "Cedritos",
                            "Pausada"});
#line 12
    await testRunner.GivenAsync("las siguientes publicaciones de \"Ana\":", ((string)(null)), table1, "Dadas ");
#line hidden
#line 19
    await testRunner.WhenAsync("un visitante anónimo consulta el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 20
    await testRunner.ThenAsync("el catálogo muestra 2 publicaciones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "barrio"});
                table2.AddRow(new string[] {
                            "Chapinero"});
                table2.AddRow(new string[] {
                            "Usaquén"});
#line 21
    await testRunner.AndAsync("el catálogo muestra las publicaciones de los barrios:", ((string)(null)), table2, "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El catálogo se filtra por operación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El catálogo se filtra por operación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task ElCatalogoSeFiltraPorOperacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El catálogo se filtra por operación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "operación",
                            "barrio",
                            "estado"});
                table3.AddRow(new string[] {
                            "arriendo",
                            "Chapinero",
                            "Publicada"});
                table3.AddRow(new string[] {
                            "venta",
                            "Usaquén",
                            "Publicada"});
#line 27
    await testRunner.GivenAsync("las siguientes publicaciones de \"Ana\":", ((string)(null)), table3, "Dadas ");
#line hidden
#line 31
    await testRunner.WhenAsync("un visitante anónimo consulta el catálogo filtrando por operación \"Rent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 32
    await testRunner.ThenAsync("el catálogo muestra 1 publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "barrio"});
                table4.AddRow(new string[] {
                            "Chapinero"});
#line 33
    await testRunner.AndAsync("el catálogo muestra las publicaciones de los barrios:", ((string)(null)), table4, "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El catálogo se puede buscar por texto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El catálogo se puede buscar por texto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task ElCatalogoSePuedeBuscarPorTexto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El catálogo se puede buscar por texto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "operación",
                            "barrio",
                            "estado"});
                table5.AddRow(new string[] {
                            "arriendo",
                            "Chapinero",
                            "Publicada"});
                table5.AddRow(new string[] {
                            "venta",
                            "Usaquén",
                            "Publicada"});
#line 38
    await testRunner.GivenAsync("las siguientes publicaciones de \"Ana\":", ((string)(null)), table5, "Dadas ");
#line hidden
#line 42
    await testRunner.WhenAsync("un visitante anónimo busca \"Usaquén\" en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 43
    await testRunner.ThenAsync("el catálogo muestra 1 publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El catálogo se pagina")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El catálogo se pagina")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task ElCatalogoSePagina()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El catálogo se pagina", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("12 publicaciones de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dadas ");
#line hidden
#line 47
    await testRunner.WhenAsync("un visitante anónimo consulta la página 2 del catálogo con 10 publicaciones por p" +
                        "ágina", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 48
    await testRunner.ThenAsync("el catálogo muestra 2 publicaciones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 49
    await testRunner.AndAsync("el total de publicaciones del catálogo es 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un visitante anónimo ve el detalle de una publicación publicada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un visitante anónimo ve el detalle de una publicación publicada")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task UnVisitanteAnonimoVeElDetalleDeUnaPublicacionPublicada()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un visitante anónimo ve el detalle de una publicación publicada", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 52
    await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 53
    await testRunner.WhenAsync("un visitante anónimo consulta la publicación en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 54
    await testRunner.ThenAsync("ve la publicación con sus 5 fotos y su precio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una publicación no publicada no existe en el catálogo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una publicación no publicada no existe en el catálogo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Borrador", "5", null, DisplayName="Una publicación no publicada no existe en el catálogo(Borrador,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("En revisión", "6", null, DisplayName="Una publicación no publicada no existe en el catálogo(En revisión,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Pausada", "7", null, DisplayName="Una publicación no publicada no existe en el catálogo(Pausada,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Suspendida", "8", null, DisplayName="Una publicación no publicada no existe en el catálogo(Suspendida,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Retirada", "9", null, DisplayName="Una publicación no publicada no existe en el catálogo(Retirada,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Cerrada", "10", null, DisplayName="Una publicación no publicada no existe en el catálogo(Cerrada,10)")]
        public async global::System.Threading.Tasks.Task UnaPublicacionNoPublicadaNoExisteEnElCatalogo(string estado, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("estado", estado);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una publicación no publicada no existe en el catálogo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.GivenAsync(string.Format("una publicación de arriendo de \"Ana\" en estado \"{0}\"", estado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 58
    await testRunner.WhenAsync("un visitante anónimo consulta la publicación en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 59
    await testRunner.ThenAsync("la publicación no se encuentra", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El resto de la API exige iniciar sesión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El resto de la API exige iniciar sesión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Catálogo público")]
        public async global::System.Threading.Tasks.Task ElRestoDeLaAPIExigeIniciarSesion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El resto de la API exige iniciar sesión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.WhenAsync("un visitante anónimo lista las publicaciones por la API privada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 72
    await testRunner.ThenAsync("la solicitud se rechaza por falta de autenticación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
