// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace NotificationLog.RentalService.IntegrationTests.Features.Listings
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CicloDeVidaDeUnaPublicacionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features/Listings", "Ciclo de vida de una publicación", "  El propietario crea la publicación en borrador, la completa y la envía a revisi" +
                "ón.\r\n  Una vez publicada puede pausarla, renovarla, cerrarla o retirarla.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CicloDeVidaDePublicacion.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("que ahora son las \"2026-10-05 09:00\" hora de Colombia", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 8
    await testRunner.AndAsync("el usuario \"Ana\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 9
    await testRunner.AndAsync("el usuario \"Pedro\" con rol Propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 10
    await testRunner.AndAsync("el usuario \"Marta\" con rol Moderador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 11
    await testRunner.AndAsync("que \"Ana\" está registrada como propietaria", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 12
    await testRunner.AndAsync("que \"Pedro\" está registrado como propietario", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Listings/CicloDeVidaDePublicacion.feature.ndjson", 30);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un propietario crea una publicación a su nombre")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un propietario crea una publicación a su nombre")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnPropietarioCreaUnaPublicacionASuNombre()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un propietario crea una publicación a su nombre", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación nace en borrador a nombre de un propietario registrado", null, tagsOfRule);
#line 16
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
      await testRunner.WhenAsync("\"Ana\" crea una publicación de arriendo a su nombre", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 18
      await testRunner.ThenAsync("la publicación queda en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 19
      await testRunner.AndAsync("la publicación pertenece a \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un propietario no puede crear publicaciones a nombre de otro")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un propietario no puede crear publicaciones a nombre de otro")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnPropietarioNoPuedeCrearPublicacionesANombreDeOtro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un propietario no puede crear publicaciones a nombre de otro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación nace en borrador a nombre de un propietario registrado", null, tagsOfRule);
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
      await testRunner.WhenAsync("\"Ana\" crea una publicación de arriendo a nombre de \"Pedro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 23
      await testRunner.ThenAsync("la solicitud se rechaza por permisos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un moderador crea una publicación a nombre de un propietario")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un moderador crea una publicación a nombre de un propietario")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnModeradorCreaUnaPublicacionANombreDeUnPropietario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un moderador crea una publicación a nombre de un propietario", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación nace en borrador a nombre de un propietario registrado", null, tagsOfRule);
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
      await testRunner.WhenAsync("\"Marta\" crea una publicación de venta a nombre de \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 27
      await testRunner.ThenAsync("la publicación queda en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 28
      await testRunner.AndAsync("la publicación pertenece a \"Ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede crear una publicación para un propietario que no existe")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede crear una publicación para un propietario que no existe")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task NoSePuedeCrearUnaPublicacionParaUnPropietarioQueNoExiste()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede crear una publicación para un propietario que no existe", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación nace en borrador a nombre de un propietario registrado", null, tagsOfRule);
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
      await testRunner.WhenAsync("\"Marta\" crea una publicación de arriendo a nombre de un propietario inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 32
      await testRunner.ThenAsync("la solicitud se rechaza por validación con el mensaje \"El propietario no está reg" +
                        "istrado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una publicación completa se envía a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una publicación completa se envía a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnaPublicacionCompletaSeEnviaARevision()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una publicación completa se envía a revisión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Para enviarla a revisión necesita datos, precio y al menos 5 fotos", null, tagsOfRule);
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" recién creada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "tipo",
                            "área",
                            "habitaciones",
                            "baños",
                            "parqueaderos",
                            "estrato",
                            "piso",
                            "ascensor",
                            "administración",
                            "ciudad",
                            "barrio",
                            "dirección"});
                table6.AddRow(new string[] {
                            "Apartment",
                            "68",
                            "2",
                            "2",
                            "1",
                            "4",
                            "5",
                            "sí",
                            "320000",
                            "Bogotá",
                            "Chapinero",
                            "Calle 60 # 9-45"});
#line 38
      await testRunner.WhenAsync("\"Ana\" actualiza los datos del inmueble con:", ((string)(null)), table6, "Cuando ");
#line hidden
#line 41
      await testRunner.AndAsync("\"Ana\" fija el precio en 1800000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 42
      await testRunner.AndAsync("\"Ana\" sube 5 fotos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 43
      await testRunner.AndAsync("\"Ana\" envía la publicación a revisión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 44
      await testRunner.ThenAsync("la publicación queda en estado \"En revisión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 45
      await testRunner.AndAsync("la publicación tiene 5 fotos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 46
      await testRunner.AndAsync("la publicación tiene precio 1800000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una publicación incompleta no se envía a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una publicación incompleta no se envía a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("sin datos del inmueble", "Faltan los datos del inmueble, la ubicación o la descripción.", "5", null, DisplayName="Una publicación incompleta no se envía a revisión(sin datos del inmueble,Faltan l" +
            "os datos del inmueble, la ubicación o la descripción.,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("sin precio", "Falta el precio de la publicación.", "6", null, DisplayName="Una publicación incompleta no se envía a revisión(sin precio,Falta el precio de l" +
            "a publicación.,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("con solo 4 fotos", "La publicación necesita al menos 5 fotos.", "7", null, DisplayName="Una publicación incompleta no se envía a revisión(con solo 4 fotos,La publicación" +
            " necesita al menos 5 fotos.,7)")]
        public async global::System.Threading.Tasks.Task UnaPublicacionIncompletaNoSeEnviaARevision(string carencia, string mensaje, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("carencia", carencia);
            argumentsOfScenario.Add("mensaje", mensaje);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una publicación incompleta no se envía a revisión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Para enviarla a revisión necesita datos, precio y al menos 5 fotos", null, tagsOfRule);
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
      await testRunner.GivenAsync(string.Format("una publicación de arriendo de \"Ana\" en estado \"Borrador\" {0}", carencia), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 50
      await testRunner.WhenAsync("\"Ana\" envía la publicación a revisión", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 51
      await testRunner.ThenAsync(string.Format("la solicitud se rechaza por regla de negocio con el mensaje \"{0}\"", mensaje), ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El canon de arriendo tiene un mínimo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El canon de arriendo tiene un mínimo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task ElCanonDeArriendoTieneUnMinimo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El canon de arriendo tiene un mínimo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Para enviarla a revisión necesita datos, precio y al menos 5 fotos", null, tagsOfRule);
#line 59
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 60
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 61
      await testRunner.WhenAsync("\"Ana\" fija el precio en 299999", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 62
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una descripción demasiado corta no pasa la validación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una descripción demasiado corta no pasa la validación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnaDescripcionDemasiadoCortaNoPasaLaValidacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una descripción demasiado corta no pasa la validación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Para enviarla a revisión necesita datos, precio y al menos 5 fotos", null, tagsOfRule);
#line 64
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 65
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 66
      await testRunner.WhenAsync("\"Ana\" actualiza los datos del inmueble con una descripción de 50 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 67
      await testRunner.ThenAsync("la solicitud se rechaza por validación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Otro propietario no puede editar la publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Otro propietario no puede editar la publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task OtroPropietarioNoPuedeEditarLaPublicacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Otro propietario no puede editar la publicación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el propietario de la publicación, un administrador o un moderador pueden ges" +
                    "tionarla", null, tagsOfRule);
#line 71
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 72
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 73
      await testRunner.WhenAsync("\"Pedro\" fija el precio en 1800000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 74
      await testRunner.ThenAsync("la solicitud se rechaza por permisos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Un moderador puede gestionar la publicación de un propietario")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un moderador puede gestionar la publicación de un propietario")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnModeradorPuedeGestionarLaPublicacionDeUnPropietario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Un moderador puede gestionar la publicación de un propietario", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Solo el propietario de la publicación, un administrador o un moderador pueden ges" +
                    "tionarla", null, tagsOfRule);
#line 76
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 77
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 78
      await testRunner.WhenAsync("\"Marta\" pausa la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 79
      await testRunner.ThenAsync("la publicación queda en estado \"Pausada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cambiar los datos de una publicación publicada la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cambiar los datos de una publicación publicada la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task CambiarLosDatosDeUnaPublicacionPublicadaLaDevuelveARevision()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cambiar los datos de una publicación publicada la devuelve a revisión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Editar una publicación visible la devuelve a revisión", null, tagsOfRule);
#line 83
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 84
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 85
      await testRunner.WhenAsync("\"Ana\" actualiza los datos del inmueble cambiando el barrio a \"Usaquén\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 86
      await testRunner.ThenAsync("la publicación queda en estado \"En revisión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 87
      await testRunner.AndAsync("la publicación no aparece en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Añadir una foto a una publicación publicada la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Añadir una foto a una publicación publicada la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task AnadirUnaFotoAUnaPublicacionPublicadaLaDevuelveARevision()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Añadir una foto a una publicación publicada la devuelve a revisión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Editar una publicación visible la devuelve a revisión", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 90
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 91
      await testRunner.WhenAsync("\"Ana\" sube 1 foto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 92
      await testRunner.ThenAsync("la publicación queda en estado \"En revisión\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cambiar el precio no la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cambiar el precio no la devuelve a revisión")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task CambiarElPrecioNoLaDevuelveARevision()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cambiar el precio no la devuelve a revisión", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Editar una publicación visible la devuelve a revisión", null, tagsOfRule);
#line 94
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 95
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 96
      await testRunner.WhenAsync("\"Ana\" fija el precio en 1950000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 97
      await testRunner.ThenAsync("la publicación queda en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 98
      await testRunner.AndAsync("la publicación tiene precio 1950000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("El precio de una publicación publicada solo cambia una vez cada 24 horas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("El precio de una publicación publicada solo cambia una vez cada 24 horas")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task ElPrecioDeUnaPublicacionPublicadaSoloCambiaUnaVezCada24Horas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("El precio de una publicación publicada solo cambia una vez cada 24 horas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Editar una publicación visible la devuelve a revisión", null, tagsOfRule);
#line 100
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 101
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 102
      await testRunner.AndAsync("que \"Ana\" fijó el precio en 1950000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 103
      await testRunner.WhenAsync("pasan 23 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 104
      await testRunner.AndAsync("\"Ana\" fija el precio en 2000000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 105
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"El precio solo se pu" +
                        "ede cambiar una vez cada 24 horas.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 106
      await testRunner.WhenAsync("pasan 2 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 107
      await testRunner.AndAsync("\"Ana\" fija el precio en 2000000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 108
      await testRunner.ThenAsync("la publicación tiene precio 2000000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Reordenar las fotos")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Reordenar las fotos")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task ReordenarLasFotos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reordenar las fotos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Las fotos se pueden quitar y reordenar", null, tagsOfRule);
#line 112
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 113
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\" con 5 fotos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 114
      await testRunner.WhenAsync("\"Ana\" reordena las fotos poniendo la última en primer lugar", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 115
      await testRunner.ThenAsync("la primera foto de la publicación es la que antes era la última", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Quitar una foto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Quitar una foto")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task QuitarUnaFoto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Quitar una foto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Las fotos se pueden quitar y reordenar", null, tagsOfRule);
#line 117
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 118
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\" con 5 fotos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 119
      await testRunner.WhenAsync("\"Ana\" quita la primera foto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 120
      await testRunner.ThenAsync("la publicación tiene 4 fotos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Pausar y reanudar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pausar y reanudar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task PausarYReanudar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pausar y reanudar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación publicada se puede pausar y reanudar", null, tagsOfRule);
#line 124
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 125
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 126
      await testRunner.WhenAsync("\"Ana\" pausa la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 127
      await testRunner.ThenAsync("la publicación queda en estado \"Pausada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 128
      await testRunner.AndAsync("la publicación no aparece en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 129
      await testRunner.WhenAsync("\"Ana\" reanuda la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 130
      await testRunner.ThenAsync("la publicación queda en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 131
      await testRunner.AndAsync("la publicación aparece en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede pausar un borrador")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede pausar un borrador")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task NoSePuedePausarUnBorrador()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede pausar un borrador", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación publicada se puede pausar y reanudar", null, tagsOfRule);
#line 133
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 134
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Borrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 135
      await testRunner.WhenAsync("\"Ana\" pausa la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 136
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"Solo se puede pausar" +
                        " una publicación en estado publicado.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Renovar dentro de la ventana extiende la vigencia un mes")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Renovar dentro de la ventana extiende la vigencia un mes")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task RenovarDentroDeLaVentanaExtiendeLaVigenciaUnMes()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Renovar dentro de la ventana extiende la vigencia un mes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("La vigencia es de un mes y se renueva cuando quedan 7 días o menos", null, tagsOfRule);
#line 140
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 141
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 142
      await testRunner.WhenAsync("pasan 25 días", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 143
      await testRunner.AndAsync("\"Ana\" renueva la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 144
      await testRunner.ThenAsync("la publicación vence el \"2026-11-30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("No se puede renovar antes de la ventana")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("No se puede renovar antes de la ventana")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task NoSePuedeRenovarAntesDeLaVentana()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No se puede renovar antes de la ventana", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("La vigencia es de un mes y se renueva cuando quedan 7 días o menos", null, tagsOfRule);
#line 146
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 147
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 148
      await testRunner.WhenAsync("pasan 10 días", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 149
      await testRunner.AndAsync("\"Ana\" renueva la publicación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 150
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"Solo se puede renova" +
                        "r una publicación vencida o a la que le queden 7 días o menos.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Cerrar una publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cerrar una publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task CerrarUnaPublicacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cerrar una publicación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación visible se cierra cuando se arrienda o se vende", null, tagsOfRule);
#line 154
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 155
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 156
      await testRunner.WhenAsync("\"Ana\" cierra la publicación con valor final 1750000 firmada el \"2026-10-04\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 157
      await testRunner.ThenAsync("la publicación queda en estado \"Cerrada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 158
      await testRunner.AndAsync("la publicación no aparece en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("La fecha de firma no puede estar en el futuro")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("La fecha de firma no puede estar en el futuro")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task LaFechaDeFirmaNoPuedeEstarEnElFuturo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("La fecha de firma no puede estar en el futuro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación visible se cierra cuando se arrienda o se vende", null, tagsOfRule);
#line 160
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 161
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 162
      await testRunner.WhenAsync("\"Ana\" cierra la publicación con valor final 1750000 firmada el \"2026-10-20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 163
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"La fecha de firma no" +
                        " puede estar en el futuro.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una publicación cerrada ya no se puede retirar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una publicación cerrada ya no se puede retirar")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnaPublicacionCerradaYaNoSePuedeRetirar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una publicación cerrada ya no se puede retirar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Una publicación visible se cierra cuando se arrienda o se vende", null, tagsOfRule);
#line 165
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 166
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Cerrada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 167
      await testRunner.WhenAsync("\"Ana\" retira la publicación con el motivo \"Ya no está disponible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 168
      await testRunner.ThenAsync("la solicitud se rechaza por regla de negocio con el mensaje \"Una publicación cerr" +
                        "ada no se puede retirar.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Retirar una publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Retirar una publicación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task RetirarUnaPublicacion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retirar una publicación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("El propietario puede retirar su publicación indicando el motivo", null, tagsOfRule);
#line 172
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 173
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 174
      await testRunner.WhenAsync("\"Ana\" retira la publicación con el motivo \"Decidí no arrendar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 175
      await testRunner.ThenAsync("la publicación queda en estado \"Retirada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 176
      await testRunner.AndAsync("la publicación no aparece en el catálogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Retirar exige un motivo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Retirar exige un motivo")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task RetirarExigeUnMotivo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retirar exige un motivo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("El propietario puede retirar su publicación indicando el motivo", null, tagsOfRule);
#line 178
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 179
      await testRunner.GivenAsync("una publicación de arriendo de \"Ana\" en estado \"Publicada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dada ");
#line hidden
#line 180
      await testRunner.WhenAsync("\"Ana\" retira la publicación con el motivo \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 181
      await testRunner.ThenAsync("la solicitud se rechaza por validación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Una publicación inexistente no se encuentra")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Una publicación inexistente no se encuentra")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ciclo de vida de una publicación")]
        public async global::System.Threading.Tasks.Task UnaPublicacionInexistenteNoSeEncuentra()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Una publicación inexistente no se encuentra", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("El propietario puede retirar su publicación indicando el motivo", null, tagsOfRule);
#line 183
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 184
    await testRunner.WhenAsync("\"Ana\" consulta una publicación inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 185
    await testRunner.ThenAsync("la publicación no se encuentra", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
