<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Aspire.Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Messaging\Messaging.csproj" />
  </ItemGroup>

</Project>
