// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationLog.NotificationService.Infrastructure.Persistence.Context;

#nullable disable

namespace NotificationLog.NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Recipients.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("_attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Attributes");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Recipients_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Recipients_IsActive");

                    b.ToTable("Recipients", (string)null);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Templates.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationTemplates_Name");

                    b.HasIndex("Channel", "IsEnabled")
                        .HasDatabaseName("IX_NotificationTemplates_Channel_IsEnabled");

                    b.ToTable("NotificationTemplates", (string)null);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Templates.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NotificationTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTemplateId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_TemplateVersions_Template_Number")
                        .HasFilter("[NotificationTemplateId] IS NOT NULL");

                    b.ToTable("TemplateVersions", (string)null);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Triggers.NotificationConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NotificationTriggerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("NotificationTriggerId", "Channel")
                        .HasDatabaseName("IX_NotificationConfigurations_Trigger_Channel");

                    b.ToTable("NotificationConfigurations", (string)null);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Triggers.NotificationTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EventKey");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationTriggers_EventKey");

                    b.ToTable("NotificationTriggers", (string)null);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Templates.TemplateVersion", b =>
                {
                    b.HasOne("NotificationLog.NotificationService.Domain.Templates.NotificationTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("NotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Triggers.NotificationConfiguration", b =>
                {
                    b.HasOne("NotificationLog.NotificationService.Domain.Triggers.NotificationTrigger", null)
                        .WithMany("Configurations")
                        .HasForeignKey("NotificationTriggerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NotificationLog.NotificationService.Domain.Templates.NotificationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Templates.NotificationTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("NotificationLog.NotificationService.Domain.Triggers.NotificationTrigger", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
